# Dependabot configuration
# Docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "UTC"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build"
      include: "scope"
    versioning-strategy: increase
    groups:
      tooling-patch-minors:
        applies-to: version-updates
        patterns:
          - "ruff*"
          - "mypy*"
          - "pytest*"
          - "mkdocs*"
          - "pip-audit*"
          - "build"
