name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff mypy coverage
          pip install pip-audit bandit[toml]

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (ruff format)
        run: ruff format --check .

      - name: Type check (mypy)
        run: mypy .

      - name: Security audit (pip-audit)
        run: |
          pip-audit -r requirements.txt || pip-audit || exit 1
        shell: bash

      - name: Security scan (bandit)
        run: |
          bandit -c bandit.yaml -r semiconductor_sim/ -f json -o bandit-results.json || true
          bandit -c bandit.yaml -r semiconductor_sim/ --severity-level medium --confidence-level medium
        shell: bash
        continue-on-error: true

      - name: Upload bandit security results
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-results-${{ matrix.python-version }}
          path: bandit-results.json
        if: always()

      - name: Run tests with coverage threshold
        run: |
          coverage run -m pytest
          coverage report --fail-under=80
          coverage xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.python-version }}
          path: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: false
        continue-on-error: true

  smoke-install:
    name: Verify install and import
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Import smoke test
        run: |
          python - <<'PY'
          import semiconductor_sim
          from semiconductor_sim.devices import PNJunctionDiode
          d = PNJunctionDiode(doping_p=1e17, doping_n=1e17, temperature=300)
          print('ok', bool(d))
          PY

  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4

  docs-build:
    name: Build Docs (strict)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Install doc tooling
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings mkdocstrings-python
      - name: Build docs strictly
        run: mkdocs build --strict
