name: Nightly Docs Validation

on:
  schedule:
    # Run every day at 1 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  issues: write

jobs:
  docs-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install doc tooling
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocstrings mkdocstrings-python

      - name: Build docs strictly
        id: build-docs
        run: |
          echo "Building documentation with strict mode..."
          mkdocs build --strict
        continue-on-error: true

      - name: Install lychee (link checker)
        uses: lycheeverse/lychee-action@v2.1.1
        with:
          args: --accept=200,202,204,301,302,307,308 --exclude=localhost --exclude=127.0.0.1 --exclude=file:// site/
          fail: true
        id: link-check
        continue-on-error: true

      - name: Upload docs artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-validation-${{ github.sha }}
          path: |
            site/
            lychee-out.md
          retention-days: 7

      - name: Create issue on docs build failure
        if: failure() && steps.build-docs.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Nightly Docs Build Failed - ${new Date().toISOString().split('T')[0]}`;
            const body = `
            ## Documentation Build Failure Report
            
            The nightly documentation build failed on commit ${context.sha}.
            
            **Issue Type:** MkDocs Build Failure
            
            **Details:**
            - Workflow: ${context.workflow}
            - Run ID: ${context.runId}
            - Run URL: ${context.payload.repository.html_url}/actions/runs/${context.runId}
            
            **Likely Causes:**
            - Invalid markdown syntax in documentation files
            - Missing or broken docstring references
            - Configuration issues in mkdocs.yml
            - Missing documentation dependencies
            
            **Next Steps:**
            1. Check the workflow logs for detailed error messages
            2. Test the documentation build locally with \`mkdocs build --strict\`
            3. Fix any documentation issues
            4. Verify the build passes before merging changes
            
            This issue was created automatically by the nightly docs validation workflow.
            `;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['documentation', 'automated', 'build-failure']
            });

      - name: Create issue on link check failure
        if: failure() && steps.link-check.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Nightly Link Check Failed - ${new Date().toISOString().split('T')[0]}`;
            const body = `
            ## Documentation Link Check Failure Report
            
            The nightly documentation link check failed on commit ${context.sha}.
            
            **Issue Type:** Broken Links in Documentation
            
            **Details:**
            - Workflow: ${context.workflow}
            - Run ID: ${context.runId}
            - Run URL: ${context.payload.repository.html_url}/actions/runs/${context.runId}
            
            **Common Causes:**
            - External websites are down or have moved
            - Internal links pointing to non-existent pages
            - Incorrect URL formatting in markdown files
            - Network connectivity issues during check
            
            **Next Steps:**
            1. Download the workflow artifacts to see the detailed link check report
            2. Check the lychee output for specific broken links
            3. Update or remove broken links in the documentation
            4. Consider excluding problematic external domains if appropriate
            
            **Link Checker Configuration:**
            - Tool: Lychee
            - Accepts: 200,202,204,301,302,307,308 status codes
            - Excludes: localhost, 127.0.0.1, file:// URLs
            
            This issue was created automatically by the nightly docs validation workflow.
            `;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['documentation', 'automated', 'link-check', 'external-links']
            });