name: Nightly Benchmarks

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  issues: write

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for ASV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install asv

      - name: Install package
        run: pip install -e .

      - name: Configure ASV
        run: |
          asv machine --yes
          
      - name: Run benchmarks
        id: benchmarks
        run: |
          # Run benchmarks for the current commit
          asv run HEAD^! --show-stderr
          
          # Generate HTML report
          asv publish
          
          # Create results summary
          asv show HEAD > benchmark_results.txt
          
        continue-on-error: true

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-${{ github.sha }}
          path: |
            .asv/results/
            .asv/html/
            benchmark_results.txt
          retention-days: 30

      - name: Create issue on failure
        if: failure() && steps.benchmarks.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Nightly Benchmark Failed - ${new Date().toISOString().split('T')[0]}`;
            const body = `
            ## Benchmark Failure Report
            
            The nightly benchmark run failed on commit ${context.sha}.
            
            **Details:**
            - Workflow: ${context.workflow}
            - Run ID: ${context.runId}
            - Run URL: ${context.payload.repository.html_url}/actions/runs/${context.runId}
            
            Please investigate the benchmark failures and fix any performance regressions.
            
            **Next Steps:**
            1. Check the workflow logs for detailed error messages
            2. Download the benchmark artifacts if available
            3. Fix any issues and re-run the benchmarks
            
            This issue was created automatically by the nightly benchmark workflow.
            `;
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['benchmark', 'automated', 'failure']
            });