name: Release Drafter

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, edited, reopened, synchronize, labeled, unlabeled, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}